global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vllm'
    static_configs:
      - targets: ['spark-2:8000']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100', 'spark-2:9100']

  - job_name: 'dcgm'
    static_configs:
      - targets: ['spark-2:9400']
